# Generated by Django 4.1.4 on 2023-01-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hack_Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hackathon Topic')),
                ('desc', models.TextField(verbose_name='Description Of Hackathon Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Hackathon Title')),
                ('desc', models.TextField(verbose_name='About Hackathon')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='edc/hackathon/posters/', verbose_name='Hackathon Poster')),
                ('reg_price', models.IntegerField(default=0, verbose_name='Registration Cost(if any)')),
                ('team_cnt', models.IntegerField(default=1, verbose_name='Max Members In 1 Team')),
                ('reg_open', models.BooleanField(default=False, verbose_name='Registration Opened?')),
                ('hack_live', models.BooleanField(default=False, verbose_name='Hackathon Started?')),
                ('on_web', models.BooleanField(default=True, verbose_name='Conduct on SciSoc Website?')),
                ('hack_or_reg_link', models.URLField(blank=True, null=True, verbose_name='Link for Registration/Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('registered', models.BooleanField(default=False, verbose_name='Registration Valid?')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Details')),
                ('team_name', models.CharField(max_length=25, verbose_name='Team Name')),
                ('hack_submitted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Time Of Hackathon Submission')),
                ('hack_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc.hackathon')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hackathon_Team_Leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sponsor Name')),
                ('logo', models.ImageField(upload_to='edc/sponsors/', verbose_name='Sponsor Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(blank=True, null=True, upload_to='edc/hackathon/')),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc.hackathon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, verbose_name='Rank In Words OR Numeric')),
                ('hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc.hackathon')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc.submission')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='members',
            field=models.ManyToManyField(to='edc.team_members'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='sponsors',
            field=models.ManyToManyField(to='edc.sponsors'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='topics',
            field=models.ManyToManyField(to='edc.hack_topics'),
        ),
    ]
