# Generated by Django 4.1.4 on 2023-01-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='show_topics',
            field=models.BooleanField(default=False, verbose_name='View Topics To All?'),
        ),
    ]
