# Generated by Django 4.1.5 on 2023-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0004_rename_payment_id_registerws_pay_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioworkshop',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Display On Web?'),
        ),
        migrations.AlterField(
            model_name='bioworkshop',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link If Conducted Online(Add on start)'),
        ),
    ]
