# Generated by Django 4.1.5 on 2023-01-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0005_bioworkshop_display_alter_bioworkshop_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Display On Web?'),
        ),
    ]
