# Generated by Django 4.1.5 on 2023-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0006_hackathon_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioworkshop',
            name='reg_link',
            field=models.URLField(blank=True, null=True, verbose_name='Add Registration Link For External Website'),
        ),
    ]
