# Generated by Django 4.1.5 on 2023-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0007_bioworkshop_reg_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerws',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Registrationn Valid ?'),
        ),
    ]
