# Generated by Django 4.1.5 on 2023-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0008_registerws_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='git_link',
            field=models.URLField(blank=True, null=True, verbose_name='Github Repository'),
        ),
        migrations.AddField(
            model_name='submission',
            name='live_host',
            field=models.URLField(blank=True, null=True, verbose_name='Live Hosted Website Link'),
        ),
    ]
