# Generated by Django 4.1.5 on 2023-01-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0009_submission_git_link_submission_live_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioworkshop',
            options={'ordering': ['-ws_time'], 'verbose_name': 'BioDesign Workshop', 'verbose_name_plural': 'BioDesign Workshops'},
        ),
        migrations.AlterModelOptions(
            name='hack_topics',
            options={'ordering': ['title'], 'verbose_name': 'Hackathon Topic', 'verbose_name_plural': 'Hackathon Topics'},
        ),
        migrations.AlterModelOptions(
            name='hackathon',
            options={'verbose_name': 'Hackathon', 'verbose_name_plural': 'Hackathons'},
        ),
        migrations.AlterModelOptions(
            name='registerws',
            options={'verbose_name': 'Workshop Registration', 'verbose_name_plural': 'eDC Workshop Registrations'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Hackathon Registration', 'verbose_name_plural': 'Hackathon Registrations'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Hackathon Result', 'verbose_name_plural': 'Hackathon Results'},
        ),
        migrations.AlterModelOptions(
            name='sponsors',
            options={'ordering': ['name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Hackathon Submission', 'verbose_name_plural': 'Hackathon Submissions'},
        ),
        migrations.AlterModelOptions(
            name='team_members',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
