# Generated by Django 4.1.5 on 2023-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0010_alter_bioworkshop_options_alter_hack_topics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Team Member Email'),
        ),
        migrations.AlterField(
            model_name='team_members',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Team Member Name'),
        ),
    ]
