# Generated by Django 4.1.5 on 2023-01-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(default='Pending', max_length=275, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(max_length=50, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=50, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=150, verbose_name='Signature ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
