# Generated by Django 4.1.5 on 2023-01-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='modelname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='uid',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
