# Generated by Django 4.1.4 on 2022-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='rating',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
