# Generated by Django 4.1.4 on 2022-12-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_alter_faq_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='rating',
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=100, unique=True),
        ),
    ]
