# Generated by Django 4.1.4 on 2022-12-24 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_remove_faq_rating_faq_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
