# Generated by Django 4.1.4 on 2022-12-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_problem_pdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name_plural': 'User Queries'},
        ),
    ]
