# Generated by Django 4.1.5 on 2023-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'User Query', 'verbose_name_plural': 'User Queries'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=1500, verbose_name='Answer(in max 1500 chars)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=100, unique=True, verbose_name='Position Number'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='desc',
            field=models.TextField(max_length=400, verbose_name='Problem Description'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Author Email'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='header',
            field=models.CharField(max_length=25, verbose_name='Problem Title'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Problem Author'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pdate',
            field=models.DateField(auto_now_add=True, verbose_name='Query Raised Date & Time'),
        ),
    ]
