# Generated by Django 4.1.4 on 2022-12-24 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('qid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_detail', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=1)),
                ('choices', models.BooleanField(default=False)),
                ('short_answer', models.BooleanField(default=False)),
                ('numerical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('reg_open', models.BooleanField(default=False)),
                ('on_web', models.BooleanField(default=True)),
                ('quiz_link', models.URLField(blank=True, null=True)),
                ('quiz_live', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('reg_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('reg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('quiz_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anastomosis.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_by_participant', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anastomosis.question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anastomosis.quiz')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anastomosis.registration')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anastomosis.quiz'),
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anastomosis.question')),
            ],
        ),
    ]
