# Generated by Django 4.1.4 on 2022-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anastomosis/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_detail',
            field=models.CharField(max_length=250),
        ),
    ]
