# Generated by Django 4.1.4 on 2022-12-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0002_question_answer_question_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_link',
            new_name='quiz_or_reg_link',
        ),
    ]
