# Generated by Django 4.1.4 on 2022-12-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0003_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_free',
        ),
    ]
