# Generated by Django 4.1.4 on 2022-12-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0004_remove_quiz_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
