# Generated by Django 4.1.4 on 2022-12-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0005_alter_question_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
