# Generated by Django 4.1.4 on 2022-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0008_registration_exam_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='quiz_submitted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
