# Generated by Django 4.1.4 on 2022-12-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0009_alter_registration_quiz_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='quiz_submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
