# Generated by Django 4.1.4 on 2022-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0011_question_matchup_question_num_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='true_false',
            field=models.BooleanField(default=False),
        ),
    ]
