# Generated by Django 4.1.5 on 2023-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastomosis', '0013_rename_payment_id_registration_pay_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='img',
            field=models.ImageField(null=True, upload_to='anastomosis/'),
        ),
    ]
