# Generated by Django 4.1.4 on 2022-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(default='latest/latest_default.png', upload_to='latest/')),
                ('link', models.URLField(null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
