# Generated by Django 4.1.4 on 2022-12-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scisoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('preference', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.AlterModelOptions(
            name='latest',
            options={'verbose_name_plural': 'Latest News'},
        ),
    ]
