# Generated by Django 4.1.5 on 2023-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scisoc', '0002_gallery_alter_latest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latest',
            options={'verbose_name': 'Latest News', 'verbose_name_plural': 'Latest News'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='hidden_title',
            field=models.CharField(max_length=50, verbose_name='Hidden Title Behind Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Gallery Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='preference',
            field=models.IntegerField(default=1, verbose_name='Higher Prefernece For Upper Display'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image',
            field=models.ImageField(default='latest/latest_default.png', upload_to='latest/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Mark Important?'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='link',
            field=models.URLField(null=True, verbose_name='Redirect Link To Website/File'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
