# Generated by Django 4.1.5 on 2023-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scisoc', '0003_alter_latest_options_alter_gallery_hidden_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='preference',
            field=models.IntegerField(default=1, verbose_name='Higher Preference For Upper Display'),
        ),
    ]
