# Generated by Django 4.1.5 on 2023-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scisoc', '0004_alter_gallery_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='size_big',
            field=models.BooleanField(default=False, verbose_name='Big( 743:410 )'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='size_images',
            field=models.BooleanField(default=True, verbose_name='Normal( 183:100 )'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='size_tall',
            field=models.BooleanField(default=False, verbose_name='Tall( 183:205 )'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='size_wide',
            field=models.BooleanField(default=False, verbose_name='Wide( 743:200 )'),
        ),
    ]
