# Generated by Django 4.1.4 on 2022-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondetails',
            name='image',
            field=models.ImageField(default='socheads/emptyuser.png', upload_to='socheads/'),
        ),
    ]
