# Generated by Django 4.1.4 on 2022-12-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdetails_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiondetails',
            options={'verbose_name_plural': 'PositionDetails'},
        ),
        migrations.RemoveField(
            model_name='positiondetails',
            name='preference',
        ),
        migrations.AddField(
            model_name='positiondetails',
            name='display_home',
            field=models.BooleanField(default=False),
        ),
    ]
