# Generated by Django 4.1.4 on 2022-12-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_positiondetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiondetails',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='event_sub',
            new_name='sub',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='fest_sub',
        ),
    ]
