# Generated by Django 4.1.4 on 2023-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_positiondetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
