# Generated by Django 4.1.4 on 2022-12-31 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question_detail', models.CharField(max_length=250, verbose_name='Question Detail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='anastomosis/', verbose_name='Question Image')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Solution(hided)')),
                ('marks', models.IntegerField(default=1, verbose_name='Marks for correct answer')),
                ('choices', models.BooleanField(default=False, verbose_name='Single/Multiple Correct Choice?')),
                ('short_answer', models.BooleanField(default=False, verbose_name='Short Answer Subjective Question?')),
                ('numerical', models.BooleanField(default=False, verbose_name='Numerical/Integer?')),
                ('true_false', models.BooleanField(default=False, verbose_name='True False Question?')),
                ('matchup', models.BooleanField(default=False, verbose_name='Match The Following Question?')),
                ('num_match', models.IntegerField(default=0, verbose_name='Number of Match options')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Quiz Title')),
                ('desc', models.TextField(max_length=500, verbose_name='About Quiz')),
                ('reg_price', models.IntegerField(default=0, verbose_name='Registration Cost(if any)')),
                ('team_cnt', models.IntegerField(default=1, verbose_name='Max Members In 1 Team')),
                ('reg_open', models.BooleanField(default=False, verbose_name='Registration Opened?')),
                ('quiz_live', models.BooleanField(default=False, verbose_name='Quiz Started?')),
                ('on_web', models.BooleanField(default=True, verbose_name='Conduct on SciSoc Website?')),
                ('quiz_or_reg_link', models.URLField(blank=True, null=True, verbose_name='Link for Registration/Quiz')),
            ],
            options={
                'verbose_name_plural': 'Medillectuals',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('registered', models.BooleanField(default=False, verbose_name='Registration Valid?')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Details')),
                ('team_name', models.CharField(max_length=25, verbose_name='Team Name')),
                ('quiz_submitted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Time Of Quiz Submission')),
                ('exam_checked', models.BooleanField(default=False, verbose_name='Exam Checked?')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_Leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_by_participant', models.TextField(blank=True, null=True, verbose_name='Solution By Participant')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Mark Correct')),
                ('question_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medquiz.question', verbose_name='Question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medquiz.quiz', verbose_name='Quiz Name')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medquiz.registration')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='members',
            field=models.ManyToManyField(to='medquiz.team_members'),
        ),
        migrations.AddField(
            model_name='registration',
            name='quiz_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medquiz.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medquiz.quiz'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50, verbose_name='Choice Detail')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Choice? (hided)')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medquiz.question')),
            ],
        ),
    ]
