# Generated by Django 4.1.4 on 2022-12-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='medquiz/posters/', verbose_name='Quiz Poster'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medquiz/questions/', verbose_name='Question Image'),
        ),
    ]
