# Generated by Django 4.1.5 on 2023-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medquiz', '0003_rename_payment_id_registration_pay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Small Description')),
                ('img', models.ImageField(upload_to='medquiz/slider/', verbose_name='Slider Image')),
            ],
        ),
    ]
