# Generated by Django 4.1.5 on 2023-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medquiz', '0004_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='desc',
            field=models.TextField(verbose_name='About Quiz'),
        ),
    ]
