# Generated by Django 4.1.4 on 2022-12-26 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curate',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Curate Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='', upload_to='curates/', verbose_name='Cover Photo')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('display', models.BooleanField(default=False, verbose_name='Display on website')),
            ],
        ),
        migrations.CreateModel(
            name='Curate_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Article Title')),
                ('description', models.TextField(verbose_name='Small Description')),
                ('image', models.ImageField(default='', upload_to='curates/', verbose_name='Article Photo')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name="Article's Author")),
                ('link', models.URLField(verbose_name='Link for the Article')),
                ('display', models.BooleanField(default=True, verbose_name='Display In Linked Curate')),
                ('curate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalclub.curate')),
            ],
        ),
    ]
