# Generated by Django 4.1.4 on 2022-12-26 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journalclub', '0002_twcaos_twcaos_link_twcaos_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FRYUMS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Curate Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='', upload_to='curates/', verbose_name='Event Photo')),
                ('live_date', models.DateTimeField(verbose_name='Start Date And Time')),
                ('display', models.BooleanField(default=False, verbose_name='Display on website')),
                ('author', models.CharField(max_length=50, verbose_name='Guest Name')),
                ('abt_author', models.CharField(blank=True, max_length=100, null=True, verbose_name='About Guest')),
            ],
        ),
        migrations.CreateModel(
            name='FRYUMS_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20, verbose_name='Platform Name')),
                ('link', models.URLField(verbose_name='Platform Link')),
                ('online', models.BooleanField(default=False, verbose_name='Display link on website?')),
                ('twcaos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalclub.fryums')),
            ],
        ),
    ]
