# Generated by Django 4.1.4 on 2022-12-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalclub', '0003_fryums_fryums_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryums',
            name='image',
            field=models.ImageField(default='', upload_to='fryums/', verbose_name='Event Photo'),
        ),
        migrations.AlterField(
            model_name='twcaos',
            name='image',
            field=models.ImageField(default='', upload_to='twcaos/', verbose_name='Cover Photo'),
        ),
    ]
