# Generated by Django 4.1.4 on 2022-12-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalclub', '0004_alter_fryums_image_alter_twcaos_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fryums_link',
            old_name='twcaos',
            new_name='fryums',
        ),
    ]
