# Generated by Django 4.1.5 on 2023-01-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalclub', '0005_rename_twcaos_fryums_link_fryums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curate',
            options={'verbose_name': 'Curate', 'verbose_name_plural': 'Curates'},
        ),
        migrations.AlterModelOptions(
            name='curate_article',
            options={'verbose_name': 'Curate Article', 'verbose_name_plural': 'Curate Articles'},
        ),
        migrations.AlterModelOptions(
            name='twcaos',
            options={'verbose_name': 'TWCAOS', 'verbose_name_plural': 'TWCAOS'},
        ),
        migrations.AlterModelOptions(
            name='twcaos_guest',
            options={'verbose_name': 'TWCAOS Guest', 'verbose_name_plural': 'TWCAOS Guests'},
        ),
        migrations.AlterModelOptions(
            name='twcaos_link',
            options={'verbose_name': 'TWCAOS Link', 'verbose_name_plural': 'TWCAOS Links'},
        ),
    ]
