# Generated by Django 4.1.5 on 2023-01-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_rename_payment_id_registerevent_pay_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='reg_link',
            field=models.URLField(blank=True, null=True, verbose_name='External registration Link'),
        ),
        migrations.AddField(
            model_name='registerevent',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Registration Valid?'),
        ),
        migrations.AddField(
            model_name='registerworkshop',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Registration Valid?'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='reg_link',
            field=models.URLField(blank=True, null=True, verbose_name='External registration Link'),
        ),
    ]
