# Generated by Django 4.1.5 on 2023-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_events_reg_link_registerevent_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='reg_link',
            field=models.URLField(blank=True, null=True, verbose_name='External Registration Link'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='live',
            field=models.BooleanField(default=False, verbose_name='Display On Web?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='reg_link',
            field=models.URLField(blank=True, null=True, verbose_name='External Registration Link'),
        ),
    ]
