# Generated by Django 4.1.5 on 2023-01-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_alter_events_reg_link_alter_insight_live_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerevent',
            old_name='workshops',
            new_name='events',
        ),
    ]
