# Generated by Django 4.1.5 on 2023-01-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_rename_workshops_registerevent_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerevent',
            name='free_collec',
            field=models.BooleanField(default=False, verbose_name='Free Collection?'),
        ),
        migrations.AddField(
            model_name='registerworkshop',
            name='free_collec',
            field=models.BooleanField(default=False, verbose_name='Free Collection?'),
        ),
    ]
