# Generated by Django 4.1.5 on 2023-01-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0006_registerevent_free_collec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['preference'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-start'], 'verbose_name_plural': 'Insight'},
        ),
        migrations.AlterModelOptions(
            name='insightresult',
            options={'verbose_name_plural': "Event's Result"},
        ),
        migrations.AlterModelOptions(
            name='registerevent',
            options={'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterModelOptions(
            name='registerworkshop',
            options={'verbose_name_plural': 'Workshop Registrations'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['preference'], 'verbose_name_plural': 'Workshops'},
        ),
    ]
