# Generated by Django 4.1.5 on 2023-02-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_alter_events_options_alter_insight_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='brochure_img',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='fest_img',
        ),
        migrations.AddField(
            model_name='insight',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='insight/images', verbose_name='Fest Image'),
        ),
        migrations.AddField(
            model_name='insight',
            name='video',
            field=models.FileField(default='insight/INSIGHT Final.mp4', upload_to='insight/videos', verbose_name='Fest Video'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(upload_to='insight/images')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.insight')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='insight/images')),
                ('position', models.CharField(max_length=50)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.insight')),
            ],
        ),
    ]
