# Generated by Django 4.1.5 on 2023-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0008_remove_insight_brochure_img_remove_insight_fest_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='video',
            field=models.FileField(default='insight/videos/INSIGHT Final.mp4', upload_to='insight/videos', verbose_name='Fest Video'),
        ),
    ]
